services:
  app:
    container_name: backend
    image: yshplsngh/testimonial:latest
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/testimonial?schema=public
      - CLIENT_ID=1072438711486-ngsjrbdriamtdeqme3qp7fa44p8kcp78.apps.googleusercontent.com
      - CLIENT_SECRET=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
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - testimonial_network


  db:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testimonial
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - testimonial_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - testimonial_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  testimonial_network:
    driver: bridge